apiVersion: apps/v1
kind: Deployment
metadata:
  name: guia-infnet
  namespace: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/metrics"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: guia-infnet
  template:
    metadata:
      labels:
        app: guia-infnet
    spec:
      containers:
        - name: guia-infnet
          image: tfmateus97/infnet-guia:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3