apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana
