apiVersion: v1
kind: Service
metadata:
  name: guia-app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: guia-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
