apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

resources:
  - namespace.yaml
  - guia-app.service.yaml
  - guia-app.deployment.yaml  
  - mysql.pvc.yaml
  - mysql.pod.yaml
  - mysql.service.yaml    