name: Build and Push Docker Image with Semantic Tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node (para ler package.json)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Extração da versão semver do package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t raphaeltorresinfnet/infnet-guia:${{ steps.version.outputs.version_tag }} .
          docker tag raphaeltorresinfnet/infnet-guia:${{ steps.version.outputs.version_tag }} raphaeltorresinfnet/infnet-guia:latest

      - name: Push da imagem com tag semântica e latest
        run: |
          docker push raphaeltorresinfnet/infnet-guia:${{ steps.version.outputs.version_tag }}
          docker push raphaeltorresinfnet/infnet-guia:latest